# Generated by Django 5.2.4 on 2025-08-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
