# Generated by Django 5.2.4 on 2026-06-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
