# Generated by Django 5.2.4 on 2026-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctions_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('art', 'Fine Art'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
