# Generated by Django 6.0.6 on 2026-06-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
